version: "3"
services:
  server:
    restart: on-failure
    container_name: server-data
    build: ./backend
    ports:
      - "8086:8086"
    networks:
      - test-network
    command: ["node", "index.js"]
    volumes:
      - data1:/app/backend
    tty: true

  node:
    restart: on-failure
    container_name: node-data
    build: ./frontend
    ports:
      - "8010:8010"
    networks:
      - test-network
    command: ["npm", "start"]
    volumes:
      - data2:/app/frontend
    tty: true

networks:
  test-network:
volumes:
  data1:
  data2:
